#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <vector>
#include <string>
#include <armadillo>

using arma::cube;
using arma::mat;
using arma::vec;

using std::map;
using std::string;
using std::vector;

namespace constants
{
    const map<string, int> ATOM_NUM = {
        {"H", 1},
        {"C", 6},
        {"N", 7},
        {"O", 8},
    };

    const vector<float> ATOMIC_BONDING_PARAMETERS = {
        9.0,  // Hydrogen
        0,    // Helium
        0,    // Lithium
        0,    // Beryllium
        0,    // Boron
        21.0, // Carbon
        25.0, // Nitrogen
        31.0, // Oxygen
        39.0, // Fluorine
        0,    // Neon
        0,    // Sodium
        0,    // Magnesium
        0,    // Aluminum
        0,    // Silicon
        0,    // Phosphorus
        0,    // Sulfur
        0,    // Chlorine
        0,    // Argon
        0,    // Potassium
        0,    // Calcium
        0,    // Scandium
        0,    // Titanium
        0,    // Vanadium
        0,    // Chromium
        0,    // Manganese
        0,    // Iron
        0,    // Cobalt
        0,    // Nickel
        0,    // Copper
        0,    // Zinc
        0,    // Gallium
        0,    // Germanium
        0,    // Arsenic
        0,    // Selenium
        0,    // Bromine
        0,    // Krypton
        0,    // Rubidium
        0,    // Strontium
        0,    // Yttrium
        0,    // Zirconium
        0,    // Niobium
        0,    // Molybdenum
        0,    // Technetium
        0,    // Ruthenium
        0,    // Rhodium
        0,    // Palladium
        0,    // Silver
        0,    // Cadmium
        0,    // Indium
        0,    // Tin
        0,    // Antimony
        0,    // Tellurium
        0,    // Iodine
        0,    // Xenon
        0,    // Cesium
        0,    // Barium
        0,    // Lanthanum
        0,    // Cerium
        0,    // Praseodymium
        0,    // Neodymium
        0,    // Promethium
        0,    // Samarium
        0,    // Europium
        0,    // Gadolinium
        0,    // Terbium
        0,    // Dysprosium
        0,    // Holmium
        0,    // Erbium
        0,    // Thulium
        0,    // Ytterbium
        0,    // Lutetium
        0,    // Hafnium
        0,    // Tantalum
        0,    // Tungsten
        0,    // Rhenium
        0,    // Osmium
        0,    // Iridium
        0,    // Platinum
        0,    // Gold
        0,    // Mercury
        0,    // Thallium
        0,    // Lead
        0,    // Bismuth
        0,    // Polonium
        0,    // Astatine
        0,    // Radon
        0,    // Francium
        0,    // Radium
        0,    // Actinium
        0,    // Thorium
        0,    // Protactinium
        0,    // Uranium
        0,    // Neptunium
        0,    // Plutonium
        0,    // Americium
        0,    // Curium
        0,    // Berkelium
        0,    // Californium
        0,    // Einsteinium
        0,    // Fermium
        0,    // Mendelevium
        0,    // Nobelium
        0,    // Lawrencium
        0,    // Rutherfordium
        0,    // Dubnium
        0,    // Seaborgium
        0,    // Bohrium
        0,    // Hassium
        0,    // Meitnerium
        0,    // Darmstadtium
        0,    // Roentgenium
        0,    // Ununbium
        0,    // Ununtrium
        0,    // Ununquadium
        0,    // Ununseptium
        0,    // Ununhexium
        0,    // Ununseptium
        0,    // Ununoctium
    };

    const vector<string> ATOM_TO_IONIZATION_ENERGY_ELECTRON_AFFINITY_PARAMS_MAPPING = {
        "7.176",                                            // Hydrogen
        "",                                                 // Helium
        "",                                                 // Lithium
        "",                                                 // Beryllium
        "",                                                 // Boron
        "14.051;5.572;5.572;5.572",                         // Carbon
        "19.316;7.275;7.275;7.275;7.275",                   // Nitrogen
        "25.390;9.111;9.111;9.111;9.111;9.111",             // Oxygen
        "32.272;11.080;11.080;11.080;11.080;11.080;11.080", // Fluorine
        "",                                                 // Neon
        "",                                                 // Sodium
        "",                                                 // Magnesium
        "",                                                 // Aluminum
        "",                                                 // Silicon
        "",                                                 // Phosphorus
        "",                                                 // Sulfur
        "",                                                 // Chlorine
        "",                                                 // Argon
        "",                                                 // Potassium
        "",                                                 // Calcium
        "",                                                 // Scandium
        "",                                                 // Titanium
        "",                                                 // Vanadium
        "",                                                 // Chromium
        "",                                                 // Manganese
        "",                                                 // Iron
        "",                                                 // Cobalt
        "",                                                 // Nickel
        "",                                                 // Copper
        "",                                                 // Zinc
        "",                                                 // Gallium
        "",                                                 // Germanium
        "",                                                 // Arsenic
        "",                                                 // Selenium
        "",                                                 // Bromine
        "",                                                 // Krypton
        "",                                                 // Rubidium
        "",                                                 // Strontium
        "",                                                 // Yttrium
        "",                                                 // Zirconium
        "",                                                 // Niobium
        "",                                                 // Molybdenum
        "",                                                 // Technetium
        "",                                                 // Ruthenium
        "",                                                 // Rhodium
        "",                                                 // Palladium
        "",                                                 // Silver
        "",                                                 // Cadmium
        "",                                                 // Indium
        "",                                                 // Tin
        "",                                                 // Antimony
        "",                                                 // Tellurium
        "",                                                 // Iodine
        "",                                                 // Xenon
        "",                                                 // Cesium
        "",                                                 // Barium
        "",                                                 // Lanthanum
        "",                                                 // Cerium
        "",                                                 // Praseodymium
        "",                                                 // Neodymium
        "",                                                 // Promethium
        "",                                                 // Samarium
        "",                                                 // Europium
        "",                                                 // Gadolinium
        "",                                                 // Terbium
        "",                                                 // Dysprosium
        "",                                                 // Holmium
        "",                                                 // Erbium
        "",                                                 // Thulium
        "",                                                 // Ytterbium
        "",                                                 // Lutetium
        "",                                                 // Hafnium
        "",                                                 // Tantalum
        "",                                                 // Tungsten
        "",                                                 // Rhenium
        "",                                                 // Osmium
        "",                                                 // Iridium
        "",                                                 // Platinum
        "",                                                 // Gold
        "",                                                 // Mercury
        "",                                                 // Thallium
        "",                                                 // Lead
        "",                                                 // Bismuth
        "",                                                 // Polonium
        "",                                                 // Astatine
        "",                                                 // Radon
        "",                                                 // Francium
        "",                                                 // Radium
        "",                                                 // Actinium
        "",                                                 // Thorium
        "",                                                 // Protactinium
        "",                                                 // Uranium
        "",                                                 // Neptunium
        "",                                                 // Plutonium
        "",                                                 // Americium
        "",                                                 // Curium
        "",                                                 // Berkelium
        "",                                                 // Californium
        "",                                                 // Einsteinium
        "",                                                 // Fermium
        "",                                                 // Mendelevium
        "",                                                 // Nobelium
        "",                                                 // Lawrencium
        "",                                                 // Rutherfordium
        "",                                                 // Dubnium
        "",                                                 // Seaborgium
        "",                                                 // Bohrium
        "",                                                 // Hassium
        "",                                                 // Meitnerium
        "",                                                 // Darmstadtium
        "",                                                 // Roentgenium
        "",                                                 // Ununbium
        "",                                                 // Ununtrium
        "",                                                 // Ununquadium
        "",                                                 // Ununpentium
        "",                                                 // Ununhexium
        "",                                                 // Ununseptium
        "",                                                 // Ununoctium
    };

    const vector<string> IONIZATION_ENERGY_ELECTRON_AFFINITY_PARAMS = {
        "7.176",         // Hydrogen
        "",              // Helium
        "",              // Lithium
        "",              // Beryllium
        "",              // Boron
        "14.051;5.572",  // Carbon
        "19.316;7.275",  // Nitrogen
        "25.390;9.111",  // Oxygen
        "32.272;11.080", // Fluorine
        "",              // Neon
        "",              // Sodium
        "",              // Magnesium
        "",              // Aluminum
        "",              // Silicon
        "",              // Phosphorus
        "",              // Sulfur
        "",              // Chlorine
        "",              // Argon
        "",              // Potassium
        "",              // Calcium
        "",              // Scandium
        "",              // Titanium
        "",              // Vanadium
        "",              // Chromium
        "",              // Manganese
        "",              // Iron
        "",              // Cobalt
        "",              // Nickel
        "",              // Copper
        "",              // Zinc
        "",              // Gallium
        "",              // Germanium
        "",              // Arsenic
        "",              // Selenium
        "",              // Bromine
        "",              // Krypton
        "",              // Rubidium
        "",              // Strontium
        "",              // Yttrium
        "",              // Zirconium
        "",              // Niobium
        "",              // Molybdenum
        "",              // Technetium
        "",              // Ruthenium
        "",              // Rhodium
        "",              // Palladium
        "",              // Silver
        "",              // Cadmium
        "",              // Indium
        "",              // Tin
        "",              // Antimony
        "",              // Tellurium
        "",              // Iodine
        "",              // Xenon
        "",              // Cesium
        "",              // Barium
        "",              // Lanthanum
        "",              // Cerium
        "",              // Praseodymium
        "",              // Neodymium
        "",              // Promethium
        "",              // Samarium
        "",              // Europium
        "",              // Gadolinium
        "",              // Terbium
        "",              // Dysprosium
        "",              // Holmium
        "",              // Erbium
        "",              // Thulium
        "",              // Ytterbium
        "",              // Lutetium
        "",              // Hafnium
        "",              // Tantalum
        "",              // Tungsten
        "",              // Rhenium
        "",              // Osmium
        "",              // Iridium
        "",              // Platinum
        "",              // Gold
        "",              // Mercury
        "",              // Thallium
        "",              // Lead
        "",              // Bismuth
        "",              // Polonium
        "",              // Astatine
        "",              // Radon
        "",              // Francium
        "",              // Radium
        "",              // Actinium
        "",              // Thorium
        "",              // Protactinium
        "",              // Uranium
        "",              // Neptunium
        "",              // Plutonium
        "",              // Americium
        "",              // Curium
        "",              // Berkelium
        "",              // Californium
        "",              // Einsteinium
        "",              // Fermium
        "",              // Mendelevium
        "",              // Nobelium
        "",              // Lawrencium
        "",              // Rutherfordium
        "",              // Dubnium
        "",              // Seaborgium
        "",              // Bohrium
        "",              // Hassium
        "",              // Meitnerium
        "",              // Darmstadtium
        "",              // Roentgenium
        "",              // Ununbium
        "",              // Ununtrium
        "",              // Ununquadium
        "",              // Ununpentium
        "",              // Ununhexium
        "",              // Ununseptium
        "",              // Ununoctium
    };

    const vector<float> S_SHELL_IONIZATION_ENERGY_ELECTRON_AFFINITY_PARAM = {
        7.176,  // Hydrogen
        0,      // Helium
        0,      // Lithium
        0,      // Beryllium
        0,      // Boron
        14.051, // Carbon
        19.316, // Nitrogen
        25.390, // Oxygen
        32.272, // Fluorine
        0,      // Neon
        0,      // Sodium
        0,      // Magnesium
        0,      // Aluminum
        0,      // Silicon
        0,      // Phosphorus
        0,      // Sulfur
        0,      // Chlorine
        0,      // Argon
        0,      // Potassium
        0,      // Calcium
        0,      // Scandium
        0,      // Titanium
        0,      // Vanadium
        0,      // Chromium
        0,      // Manganese
        0,      // Iron
        0,      // Cobalt
        0,      // Nickel
        0,      // Copper
        0,      // Zinc
        0,      // Gallium
        0,      // Germanium
        0,      // Arsenic
        0,      // Selenium
        0,      // Bromine
        0,      // Krypton
        0,      // Rubidium
        0,      // Strontium
        0,      // Yttrium
        0,      // Zirconium
        0,      // Niobium
        0,      // Molybdenum
        0,      // Technetium
        0,      // Ruthenium
        0,      // Rhodium
        0,      // Palladium
        0,      // Silver
        0,      // Cadmium
        0,      // Indium
        0,      // Tin
        0,      // Antimony
        0,      // Tellurium
        0,      // Iodine
        0,      // Xenon
        0,      // Cesium
        0,      // Barium
        0,      // Lanthanum
        0,      // Cerium
        0,      // Praseodymium
        0,      // Neodymium
        0,      // Promethium
        0,      // Samarium
        0,      // Europium
        0,      // Gadolinium
        0,      // Terbium
        0,      // Dysprosium
        0,      // Holmium
        0,      // Erbium
        0,      // Thulium
        0,      // Ytterbium
        0,      // Lutetium
        0,      // Hafnium
        0,      // Tantalum
        0,      // Tungsten
        0,      // Rhenium
        0,      // Osmium
        0,      // Iridium
        0,      // Platinum
        0,      // Gold
        0,      // Mercury
        0,      // Thallium
        0,      // Lead
        0,      // Bismuth
        0,      // Polonium
        0,      // Astatine
        0,      // Radon
        0,      // Francium
        0,      // Radium
        0,      // Actinium
        0,      // Thorium
        0,      // Protactinium
        0,      // Uranium
        0,      // Neptunium
        0,      // Plutonium
        0,      // Americium
        0,      // Curium
        0,      // Berkelium
        0,      // Californium
        0,      // Einsteinium
        0,      // Fermium
        0,      // Mendelevium
        0,      // Nobelium
        0,      // Lawrencium
        0,      // Rutherfordium
        0,      // Dubnium
        0,      // Seaborgium
        0,      // Bohrium
        0,      // Hassium
        0,      // Meitnerium
        0,      // Darmstadtium
        0,      // Roentgenium
        0,      // Ununbium
        0,      // Ununtrium
        0,      // Ununquadium
        0,      // Ununpentium
        0,      // Ununhexium
        0,      // Ununseptium
        0,      // Ununoctium
    };

    const vector<float> P_SHELL_IONIZATION_ENERGY_ELECTRON_AFFINITY_PARAM = {
        0.0,    // Hydrogen N/A since hydrogen only has s shell
        0,      // Helium
        0,      // Lithium
        0,      // Beryllium
        0,      // Boron
        5.572,  // Carbon
        7.275,  // Nitrogen
        9.111,  // Oxygen
        11.080, // Fluorine
        0,      // Neon
        0,      // Sodium
        0,      // Magnesium
        0,      // Aluminum
        0,      // Silicon
        0,      // Phosphorus
        0,      // Sulfur
        0,      // Chlorine
        0,      // Argon
        0,      // Potassium
        0,      // Calcium
        0,      // Scandium
        0,      // Titanium
        0,      // Vanadium
        0,      // Chromium
        0,      // Manganese
        0,      // Iron
        0,      // Cobalt
        0,      // Nickel
        0,      // Copper
        0,      // Zinc
        0,      // Gallium
        0,      // Germanium
        0,      // Arsenic
        0,      // Selenium
        0,      // Bromine
        0,      // Krypton
        0,      // Rubidium
        0,      // Strontium
        0,      // Yttrium
        0,      // Zirconium
        0,      // Niobium
        0,      // Molybdenum
        0,      // Technetium
        0,      // Ruthenium
        0,      // Rhodium
        0,      // Palladium
        0,      // Silver
        0,      // Cadmium
        0,      // Indium
        0,      // Tin
        0,      // Antimony
        0,      // Tellurium
        0,      // Iodine
        0,      // Xenon
        0,      // Cesium
        0,      // Barium
        0,      // Lanthanum
        0,      // Cerium
        0,      // Praseodymium
        0,      // Neodymium
        0,      // Promethium
        0,      // Samarium
        0,      // Europium
        0,      // Gadolinium
        0,      // Terbium
        0,      // Dysprosium
        0,      // Holmium
        0,      // Erbium
        0,      // Thulium
        0,      // Ytterbium
        0,      // Lutetium
        0,      // Hafnium
        0,      // Tantalum
        0,      // Tungsten
        0,      // Rhenium
        0,      // Osmium
        0,      // Iridium
        0,      // Platinum
        0,      // Gold
        0,      // Mercury
        0,      // Thallium
        0,      // Lead
        0,      // Bismuth
        0,      // Polonium
        0,      // Astatine
        0,      // Radon
        0,      // Francium
        0,      // Radium
        0,      // Actinium
        0,      // Thorium
        0,      // Protactinium
        0,      // Uranium
        0,      // Neptunium
        0,      // Plutonium
        0,      // Americium
        0,      // Curium
        0,      // Berkelium
        0,      // Californium
        0,      // Einsteinium
        0,      // Fermium
        0,      // Mendelevium
        0,      // Nobelium
        0,      // Lawrencium
        0,      // Rutherfordium
        0,      // Dubnium
        0,      // Seaborgium
        0,      // Bohrium
        0,      // Hassium
        0,      // Meitnerium
        0,      // Darmstadtium
        0,      // Roentgenium
        0,      // Ununbium
        0,      // Ununtrium
        0,      // Ununquadium
        0,      // Ununpentium
        0,      // Ununhexium
        0,      // Ununseptium
        0,      // Ununoctium
    };

    const vector<string>
        BASIS_SETS = {
            "3.42525091 0.15432897;0.62391373 0.53532814;0.1688554 0.44463454",                                                       // Hydrogen
            "",                                                                                                                       // Helium
            "",                                                                                                                       // Lithium
            "",                                                                                                                       // Beryllium
            "",                                                                                                                       // Boron
            "2.94124940 -0.09996723 0.15591627;0.68348310 0.39951283 0.60768372;0.22228990 0.70011547 0.39195739",                    // Carbon
            "3.780455879E -0.09996722919 0.1559162750;0.8784966449 0.3995128261 0.6076837186;0.2857143744 0.7001154689 0.3919573931", // Nitrogen
            "5.033151319 -0.09996722919 0.1559162750;1.169596125 0.3995128261 0.6076837186;0.3803889600 0.7001154689 0.3919573931",   // Oxygen
            "6.464803249 -0.09996722919 0.1559162750;1.502281245 0.3995128261 0.6076837186;0.4885884864 0.7001154689 0.3919573931",   // Fluorine
            "",                                                                                                                       // Neon
            "",                                                                                                                       // Sodium
            "",                                                                                                                       // Magnesium
            "",                                                                                                                       // Aluminum
            "",                                                                                                                       // Silicon
            "",                                                                                                                       // Phosphorus
            "",                                                                                                                       // Sulfur
            "",                                                                                                                       // Chlorine
            "",                                                                                                                       // Argon
            "",                                                                                                                       // Potassium
            "",                                                                                                                       // Calcium
            "",                                                                                                                       // Scandium
            "",                                                                                                                       // Titanium
            "",                                                                                                                       // Vanadium
            "",                                                                                                                       // Chromium
            "",                                                                                                                       // Manganese
            "",                                                                                                                       // Iron
            "",                                                                                                                       // Cobalt
            "",                                                                                                                       // Nickel
            "",                                                                                                                       // Copper
            "",                                                                                                                       // Zinc
            "",                                                                                                                       // Gallium
            "",                                                                                                                       // Germanium
            "",                                                                                                                       // Arsenic
            "",                                                                                                                       // Selenium
            "",                                                                                                                       // Bromine
            "",                                                                                                                       // Krypton
            "",                                                                                                                       // Rubidium
            "",                                                                                                                       // Strontium
            "",                                                                                                                       // Yttrium
            "",                                                                                                                       // Zirconium
            "",                                                                                                                       // Niobium
            "",                                                                                                                       // Molybdenum
            "",                                                                                                                       // Technetium
            "",                                                                                                                       // Ruthenium
            "",                                                                                                                       // Rhodium
            "",                                                                                                                       // Palladium
            "",                                                                                                                       // Silver
            "",                                                                                                                       // Cadmium
            "",                                                                                                                       // Indium
            "",                                                                                                                       // Tin
            "",                                                                                                                       // Antimony
            "",                                                                                                                       // Tellurium
            "",                                                                                                                       // Iodine
            "",                                                                                                                       // Xenon
            "",                                                                                                                       // Cesium
            "",                                                                                                                       // Barium
            "",                                                                                                                       // Lanthanum
            "",                                                                                                                       // Cerium
            "",                                                                                                                       // Praseodymium
            "",                                                                                                                       // Neodymium
            "",                                                                                                                       // Promethium
            "",                                                                                                                       // Samarium
            "",                                                                                                                       // Europium
            "",                                                                                                                       // Gadolinium
            "",                                                                                                                       // Terbium
            "",                                                                                                                       // Dysprosium
            "",                                                                                                                       // Holmium
            "",                                                                                                                       // Erbium
            "",                                                                                                                       // Thulium
            "",                                                                                                                       // Ytterbium
            "",                                                                                                                       // Lutetium
            "",                                                                                                                       // Hafnium
            "",                                                                                                                       // Tantalum
            "",                                                                                                                       // Tungsten
            "",                                                                                                                       // Rhenium
            "",                                                                                                                       // Osmium
            "",                                                                                                                       // Iridium
            "",                                                                                                                       // Platinum
            "",                                                                                                                       // Gold
            "",                                                                                                                       // Mercury
            "",                                                                                                                       // Thallium
            "",                                                                                                                       // Lead
            "",                                                                                                                       // Bismuth
            "",                                                                                                                       // Polonium
            "",                                                                                                                       // Astatine
            "",                                                                                                                       // Radon
            "",                                                                                                                       // Francium
            "",                                                                                                                       // Radium
            "",                                                                                                                       // Actinium
            "",                                                                                                                       // Thorium
            "",                                                                                                                       // Protactinium
            "",                                                                                                                       // Uranium
            "",                                                                                                                       // Neptunium
            "",                                                                                                                       // Plutonium
            "",                                                                                                                       // Americium
            "",                                                                                                                       // Curium
            "",                                                                                                                       // Berkelium
            "",                                                                                                                       // Californium
            "",                                                                                                                       // Einsteinium
            "",                                                                                                                       // Fermium
            "",                                                                                                                       // Mendelevium
            "",                                                                                                                       // Nobelium
            "",                                                                                                                       // Lawrencium
            "",                                                                                                                       // Rutherfordium
            "",                                                                                                                       // Dubnium
            "",                                                                                                                       // Seaborgium
            "",                                                                                                                       // Bohrium
            "",                                                                                                                       // Hassium
            "",                                                                                                                       // Meitnerium
            "",                                                                                                                       // Darmstadtium
            "",                                                                                                                       // Roentgenium
            "",                                                                                                                       // Ununbium
            "",                                                                                                                       // Ununtrium
            "",                                                                                                                       // Ununquadium
            "",                                                                                                                       // Ununpentium
            "",                                                                                                                       // Ununhexium
            "",                                                                                                                       // Ununseptium
            "",                                                                                                                       // Ununoctium
    };

    // constants have internal linkage by default
    const vector<string> ATOM_SYMBOLS = {
        "H",   // Hydrogen
        "He",  // Helium
        "Li",  // Lithium
        "Be",  // Beryllium
        "B",   // Boron
        "C",   // Carbon
        "N",   // Nitrogen
        "O",   // Oxygen
        "F",   // Fluorine
        "Ne",  // Neon
        "Na",  // Sodium
        "Mg",  // Magnesium
        "Al",  // Aluminum
        "Si",  // Silicon
        "P",   // Phosphorus
        "S",   // Sulfur
        "Cl",  // Chlorine
        "Ar",  // Argon
        "K",   // Potassium
        "Ca",  // Calcium
        "Sc",  // Scandium
        "Ti",  // Titanium
        "V",   // Vanadium
        "Cr",  // Chromium
        "Mn",  // Manganese
        "Fe",  // Iron
        "Co",  // Cobalt
        "Ni",  // Nickel
        "Cu",  // Copper
        "Zn",  // Zinc
        "Ga",  // Gallium
        "Ge",  // Germanium
        "As",  // Arsenic
        "Se",  // Selenium
        "Br",  // Bromine
        "Kr",  // Krypton
        "Rb",  // Rubidium
        "Sr",  // Strontium
        "Y",   // Yttrium
        "Zr",  // Zirconium
        "Nb",  // Niobium
        "Mo",  // Molybdenum
        "Tc",  // Technetium
        "Ru",  // Ruthenium
        "Rh",  // Rhodium
        "Pd",  // Palladium
        "Ag",  // Silver
        "Cd",  // Cadmium
        "In",  // Indium
        "Sn",  // Tin
        "Sb",  // Antimony
        "Te",  // Tellurium
        "I",   // Iodine
        "Xe",  // Xenon
        "Cs",  // Cesium
        "Ba",  // Barium
        "La",  // Lanthanum
        "Ce",  // Cerium
        "Pr",  // Praseodymium
        "Nd",  // Neodymium
        "Pm",  // Promethium
        "Sm",  // Samarium
        "Eu",  // Europium
        "Gd",  // Gadolinium
        "Tb",  // Terbium
        "Dy",  // Dysprosium
        "Ho",  // Holmium
        "Er",  // Erbium
        "Tm",  // Thulium
        "Yb",  // Ytterbium
        "Lu",  // Lutetium
        "Hf",  // Hafnium
        "Ta",  // Tantalum
        "W",   // Tungsten
        "Re",  // Rhenium
        "Os",  // Osmium
        "Ir",  // Iridium
        "Pt",  // Platinum
        "Au",  // Gold
        "Hg",  // Mercury
        "Tl",  // Thallium
        "Pb",  // Lead
        "Bi",  // Bismuth
        "Po",  // Polonium
        "At",  // Astatine
        "Rn",  // Radon
        "Fr",  // Francium
        "Ra",  // Radium
        "Ac",  // Actinium
        "Th",  // Thorium
        "Pa",  // Protactinium
        "U",   // Uranium
        "Np",  // Neptunium
        "Pu",  // Plutonium
        "Am",  // Americium
        "Cm",  // Curium
        "Bk",  // Berkelium
        "Cf",  // Californium
        "Es",  // Einsteinium
        "Fm",  // Fermium
        "Md",  // Mendelevium
        "No",  // Nobelium
        "Lr",  // Lawrencium
        "Rf",  // Rutherfordium
        "Db",  // Dubnium
        "Sg",  // Seaborgium
        "Bh",  // Bohrium
        "Hs",  // Hassium
        "Mt",  // Meitnerium
        "Ds",  // Darmstadtium
        "Rg",  // Roentgenium
        "Uub", // Ununbium
        "Uut", // Ununtrium
        "Uuq", // Ununquadium
        "Uup", // Ununpentium
        "Uuh", // Ununhexium
        "Uus", // Ununseptium
        "Uuo", // Ununoctium
    };

    const vector<int> ATOM_BASIS_FN_MAP = {
        1, // Hydrogen
        0, // Helium
        0, // Lithium
        0, // Beryllium
        0, // Boron
        4, // Carbon
        4, // Nitrogen
        4, // Oxygen
        0, // Fluorine
        0, // Neon
        0, // Sodium
        0, // Magnesium
        0, // Aluminum
        0, // Silicon
        0, // Phosphorus
        0, // Sulfur
        0, // Chlorine
        0, // Argon
        0, // Potassium
        0, // Calcium
        0, // Scandium
        0, // Titanium
        0, // Vanadium
        0, // Chromium
        0, // Manganese
        0, // Iron
        0, // Cobalt
        0, // Nickel
        0, // Copper
        0, // Zinc
        0, // Gallium
        0, // Germanium
        0, // Arsenic
        0, // Selenium
        0, // Bromine
        0, // Krypton
        0, // Rubidium
        0, // Strontium
        0, // Yttrium
        0, // Zirconium
        0, // Niobium
        0, // Molybdenum
        0, // Technetium
        0, // Ruthenium
        0, // Rhodium
        0, // Palladium
        0, // Silver
        0, // Cadmium
        0, // Indium
        0, // Tin
        0, // Antimony
        0, // Tellurium
        0, // Iodine
        0, // Xenon
        0, // Cesium
        0, // Barium
        0, // Lanthanum
        0, // Cerium
        0, // Praseodymium
        0, // Neodymium
        0, // Promethium
        0, // Samarium
        0, // Europium
        0, // Gadolinium
        0, // Terbium
        0, // Dysprosium
        0, // Holmium
        0, // Erbium
        0, // Thulium
        0, // Ytterbium
        0, // Lutetium
        0, // Hafnium
        0, // Tantalum
        0, // Tungsten
        0, // Rhenium
        0, // Osmium
        0, // Iridium
        0, // Platinum
        0, // Gold
        0, // Mercury
        0, // Thallium
        0, // Lead
        0, // Bismuth
        0, // Polonium
        0, // Astatine
        0, // Radon
        0, // Francium
        0, // Radium
        0, // Actinium
        0, // Thorium
        0, // Protactinium
        0, // Uranium
        0, // Neptunium
        0, // Plutonium
        0, // Americium
        0, // Curium
        0, // Berkelium
        0, // Californium
        0, // Einsteinium
        0, // Fermium
        0, // Mendelevium
        0, // Nobelium
        0, // Lawrencium
        0, // Rutherfordium
        0, // Dubnium
        0, // Seaborgium
        0, // Bohrium
        0, // Hassium
        0, // Meitnerium
        0, // Darmstadtium
        0, // Roentgenium
        0, // Ununbium
        0, // Ununtrium
        0, // Ununquadium
        0, // Ununpentium
        0, // Ununhexium
        0, // Ununseptium
        0, // Ununoctium
    };

    const vector<int> VALENCE_ATOMIC_NUM = {
        1, // Hydrogen
        0, // Helium
        0, // Lithium
        0, // Beryllium
        0, // Boron
        4, // Carbon
        5, // Nitrogen
        6, // Oxygen
        0, // Fluorine
        0, // Neon
        0, // Sodium
        0, // Magnesium
        0, // Aluminum
        0, // Silicon
        0, // Phosphorus
        0, // Sulfur
        0, // Chlorine
        0, // Argon
        0, // Potassium
        0, // Calcium
        0, // Scandium
        0, // Titanium
        0, // Vanadium
        0, // Chromium
        0, // Manganese
        0, // Iron
        0, // Cobalt
        0, // Nickel
        0, // Copper
        0, // Zinc
        0, // Gallium
        0, // Germanium
        0, // Arsenic
        0, // Selenium
        0, // Bromine
        0, // Krypton
        0, // Rubidium
        0, // Strontium
        0, // Yttrium
        0, // Zirconium
        0, // Niobium
        0, // Molybdenum
        0, // Technetium
        0, // Ruthenium
        0, // Rhodium
        0, // Palladium
        0, // Silver
        0, // Cadmium
        0, // Indium
        0, // Tin
        0, // Antimony
        0, // Tellurium
        0, // Iodine
        0, // Xenon
        0, // Cesium
        0, // Barium
        0, // Lanthanum
        0, // Cerium
        0, // Praseodymium
        0, // Neodymium
        0, // Promethium
        0, // Samarium
        0, // Europium
        0, // Gadolinium
        0, // Terbium
        0, // Dysprosium
        0, // Holmium
        0, // Erbium
        0, // Thulium
        0, // Ytterbium
        0, // Lutetium
        0, // Hafnium
        0, // Tantalum
        0, // Tungsten
        0, // Rhenium
        0, // Osmium
        0, // Iridium
        0, // Platinum
        0, // Gold
        0, // Mercury
        0, // Thallium
        0, // Lead
        0, // Bismuth
        0, // Polonium
        0, // Astatine
        0, // Radon
        0, // Francium
        0, // Radium
        0, // Actinium
        0, // Thorium
        0, // Protactinium
        0, // Uranium
        0, // Neptunium
        0, // Plutonium
        0, // Americium
        0, // Curium
        0, // Berkelium
        0, // Californium
        0, // Einsteinium
        0, // Fermium
        0, // Mendelevium
        0, // Nobelium
        0, // Lawrencium
        0, // Rutherfordium
        0, // Dubnium
        0, // Seaborgium
        0, // Bohrium
        0, // Hassium
        0, // Meitnerium
        0, // Darmstadtium
        0, // Roentgenium
        0, // Ununbium
        0, // Ununtrium
        0, // Ununquadium
        0, // Ununpentium
        0, // Ununhexium
        0, // Ununseptium
        0, // Ununoctium
    };

    const float CONVERSION_FACTOR = 27.211;

    const vector<int>
        SECONDARY_QUANTUM_NUMBER_COMBINATIONS = {
            1,
            3,
            6,
            10,
            15,
            21,
    };

    const string S_SHELL_CONTRACTION_COEFFS = "0.15432897; 0.53532814; 0.44463454";

    const vector<string>
        ATOM_COEFFS_MAP = {
            "3.42525091 0.15432897;0.62391373 0.53532814;0.1688554 0.44463454",                                                     // Hydrogen
            "",                                                                                                                     // Helium
            "",                                                                                                                     // Lithium
            "",                                                                                                                     // Beryllium
            "",                                                                                                                     // Boron
            "2.94124940 -0.09996723 0.15591627;0.68348310 0.39951283 0.60768372;0.22228990 0.70011547 0.39195739",                  // Carbon
            "3.780455879 -0.09996723 0.15591627;0.8784966449 0.3995128261 0.6076837186;0.2857143744 0.7001154689 0.3919573931",     // Nitrogen
            "5.033151319 -0.09996722919 0.1559162750;1.169596125 0.3995128261 0.6076837186;0.3803889600 0.7001154689 0.3919573931", // Oxygen
            "",                                                                                                                     // Fluorine
            "",                                                                                                                     // Neon
            "",                                                                                                                     // Sodium
            "",                                                                                                                     // Magnesium
            "",                                                                                                                     // Aluminum
            "",                                                                                                                     // Silicon
            "",                                                                                                                     // Phosphorus
            "",                                                                                                                     // Sulfur
            "",                                                                                                                     // Chlorine
            "",                                                                                                                     // Argon
            "",                                                                                                                     // Potassium
            "",                                                                                                                     // Calcium
            "",                                                                                                                     // Scandium
            "",                                                                                                                     // Titanium
            "",                                                                                                                     // Vanadium
            "",                                                                                                                     // Chromium
            "",                                                                                                                     // Manganese
            "",                                                                                                                     // Iron
            "",                                                                                                                     // Cobalt
            "",                                                                                                                     // Nickel
            "",                                                                                                                     // Copper
            "",                                                                                                                     // Zinc
            "",                                                                                                                     // Gallium
            "",                                                                                                                     // Germanium
            "",                                                                                                                     // Arsenic
            "",                                                                                                                     // Selenium
            "",                                                                                                                     // Bromine
            "",                                                                                                                     // Krypton
            "",                                                                                                                     // Rubidium
            "",                                                                                                                     // Strontium
            "",                                                                                                                     // Yttrium
            "",                                                                                                                     // Zirconium
            "",                                                                                                                     // Niobium
            "",                                                                                                                     // Molybdenum
            "",                                                                                                                     // Technetium
            "",                                                                                                                     // Ruthenium
            "",                                                                                                                     // Rhodium
            "",                                                                                                                     // Palladium
            "",                                                                                                                     // Silver
            "",                                                                                                                     // Cadmium
            "",                                                                                                                     // Indium
            "",                                                                                                                     // Tin
            "",                                                                                                                     // Antimony
            "",                                                                                                                     // Tellurium
            "",                                                                                                                     // Iodine
            "",                                                                                                                     // Xenon
            "",                                                                                                                     // Cesium
            "",                                                                                                                     // Barium
            "",                                                                                                                     // Lanthanum
            "",                                                                                                                     // Cerium
            "",                                                                                                                     // Praseodymium
            "",                                                                                                                     // Neodymium
            "",                                                                                                                     // Promethium
            "",                                                                                                                     // Samarium
            "",                                                                                                                     // Europium
            "",                                                                                                                     // Gadolinium
            "",                                                                                                                     // Terbium
            "",                                                                                                                     // Dysprosium
            "",                                                                                                                     // Holmium
            "",                                                                                                                     // Erbium
            "",                                                                                                                     // Thulium
            "",                                                                                                                     // Ytterbium
            "",                                                                                                                     // Lutetium
            "",                                                                                                                     // Hafnium
            "",                                                                                                                     // Tantalum
            "",                                                                                                                     // Tungsten
            "",                                                                                                                     // Rhenium
            "",                                                                                                                     // Osmium
            "",                                                                                                                     // Iridium
            "",                                                                                                                     // Platinum
            "",                                                                                                                     // Gold
            "",                                                                                                                     // Mercury
            "",                                                                                                                     // Thallium
            "",                                                                                                                     // Lead
            "",                                                                                                                     // Bismuth
            "",                                                                                                                     // Polonium
            "",                                                                                                                     // Astatine
            "",                                                                                                                     // Radon
            "",                                                                                                                     // Francium
            "",                                                                                                                     // Radium
            "",                                                                                                                     // Actinium
            "",                                                                                                                     // Thorium
            "",                                                                                                                     // Protactinium
            "",                                                                                                                     // Uranium
            "",                                                                                                                     // Neptunium
            "",                                                                                                                     // Plutonium
            "",                                                                                                                     // Americium
            "",                                                                                                                     // Curium
            "",                                                                                                                     // Berkelium
            "",                                                                                                                     // Californium
            "",                                                                                                                     // Einsteinium
            "",                                                                                                                     // Fermium
            "",                                                                                                                     // Mendelevium
            "",                                                                                                                     // Nobelium
            "",                                                                                                                     // Lawrencium
            "",                                                                                                                     // Rutherfordium
            "",                                                                                                                     // Dubnium
            "",                                                                                                                     // Seaborgium
            "",                                                                                                                     // Bohrium
            "",                                                                                                                     // Hassium
            "",                                                                                                                     // Meitnerium
            "",                                                                                                                     // Darmstadtium
            "",                                                                                                                     // Roentgenium
            "",                                                                                                                     // Ununbium
            "",                                                                                                                     // Ununtrium
            "",                                                                                                                     // Ununquadium
            "",                                                                                                                     // Ununpentium
            "",                                                                                                                     // Ununhexium
            "",                                                                                                                     // Ununseptium
            "",                                                                                                                     // Ununoctium
    };

    const vector<vector<string>> VALENCE_SHELL_CONFIGS = {
        {"(1s)"},         // Hydrogen
        {},               // Helium
        {},               // Lithium
        {},               // Beryllium
        {},               // Boron
        {"(2s)", "(2p)"}, // Carbon
        {"(2s)", "(2p)"}, // Nitrogen
        {"(2s)", "(2p)"}, // Oxygen
        {},               // Fluorine
        {},               // Neon
        {},               // Sodium
        {},               // Magnesium
        {},               // Aluminum
        {},               // Silicon
        {},               // Phosphorus
        {},               // Sulfur
        {},               // Chlorine
        {},               // Argon
        {},               // Potassium
        {},               // Calcium
        {},               // Scandium
        {},               // Titanium
        {},               // Vanadium
        {},               // Chromium
        {},               // Manganese
        {},               // Iron
        {},               // Cobalt
        {},               // Nickel
        {},               // Copper
        {},               // Zinc
        {},               // Gallium
        {},               // Germanium
        {},               // Arsenic
        {},               // Selenium
        {},               // Bromine
        {},               // Krypton
        {},               // Rubidium
        {},               // Strontium
        {},               // Yttrium
        {},               // Zirconium
        {},               // Niobium
        {},               // Molybdenum
        {},               // Technetium
        {},               // Ruthenium
        {},               // Rhodium
        {},               // Palladium
        {},               // Silver
        {},               // Cadmium
        {},               // Indium
        {},               // Tin
        {},               // Antimony
        {},               // Tellurium
        {},               // Iodine
        {},               // Xenon
        {},               // Cesium
        {},               // Barium
        {},               // Lanthanum
        {},               // Cerium
        {},               // Praseodymium
        {},               // Neodymium
        {},               // Promethium
        {},               // Samarium
        {},               // Europium
        {},               // Gadolinium
        {},               // Terbium
        {},               // Dysprosium
        {},               // Holmium
        {},               // Erbium
        {},               // Thulium
        {},               // Ytterbium
        {},               // Lutetium
        {},               // Hafnium
        {},               // Tantalum
        {},               // Tungsten
        {},               // Rhenium
        {},               // Osmium
        {},               // Iridium
        {},               // Platinum
        {},               // Gold
        {},               // Mercury
        {},               // Thallium
        {},               // Lead
        {},               // Bismuth
        {},               // Polonium
        {},               // Astatine
        {},               // Radon
        {},               // Francium
        {},               // Radium
        {},               // Actinium
        {},               // Thorium
        {},               // Protactinium
        {},               // Uranium
        {},               // Neptunium
        {},               // Plutonium
        {},               // Americium
        {},               // Curium
        {},               // Berkelium
        {},               // Californium
        {},               // Einsteinium
        {},               // Fermium
        {},               // Mendelevium
        {},               // Nobelium
        {},               // Lawrencium
        {},               // Rutherfordium
        {},               // Dubnium
        {},               // Seaborgium
        {},               // Bohrium
        {},               // Hassium
        {},               // Meitnerium
        {},               // Darmstadtium
        {},               // Roentgenium
        {},               // Ununbium
        {},               // Ununtrium
        {},               // Ununquadium
        {},               // Ununpentium
        {},               // Ununhexium
        {},               // Ununseptium
        {},               // Ununoctium
    };

    const double K_VAL = 1.75;

    const map<string, double> EXTENDED_HUCKEL_MAP = {
        {"H(1s)", -13.6},
        {"C(2s)", -21.4},
        {"C(2p)", -11.4},
        {"N(2s)", -26.0},
        {"N(2p)", -13.4},
    };

    const vector<string> ATOM_ANGULAR_MOMENTUM_MAP = {
        "0",   // Hydrogen
        "",    // Helium
        "",    // Lithium
        "",    // Beryllium
        "",    // Boron
        "0 1", // Carbon
        "0 1", // Nitrogen
        "0 1", // Oxygen
        "",    // Fluorine
        "",    // Neon
        "",    // Sodium
        "",    // Magnesium
        "",    // Aluminum
        "",    // Silicon
        "",    // Phosphorus
        "",    // Sulfur
        "",    // Chlorine
        "",    // Argon
        "",    // Potassium
        "",    // Calcium
        "",    // Scandium
        "",    // Titanium
        "",    // Vanadium
        "",    // Chromium
        "",    // Manganese
        "",    // Iron
        "",    // Cobalt
        "",    // Nickel
        "",    // Copper
        "",    // Zinc
        "",    // Gallium
        "",    // Germanium
        "",    // Arsenic
        "",    // Selenium
        "",    // Bromine
        "",    // Krypton
        "",    // Rubidium
        "",    // Strontium
        "",    // Yttrium
        "",    // Zirconium
        "",    // Niobium
        "",    // Molybdenum
        "",    // Technetium
        "",    // Ruthenium
        "",    // Rhodium
        "",    // Palladium
        "",    // Silver
        "",    // Cadmium
        "",    // Indium
        "",    // Tin
        "",    // Antimony
        "",    // Tellurium
        "",    // Iodine
        "",    // Xenon
        "",    // Cesium
        "",    // Barium
        "",    // Lanthanum
        "",    // Cerium
        "",    // Praseodymium
        "",    // Neodymium
        "",    // Promethium
        "",    // Samarium
        "",    // Europium
        "",    // Gadolinium
        "",    // Terbium
        "",    // Dysprosium
        "",    // Holmium
        "",    // Erbium
        "",    // Thulium
        "",    // Ytterbium
        "",    // Lutetium
        "",    // Hafnium
        "",    // Tantalum
        "",    // Tungsten
        "",    // Rhenium
        "",    // Osmium
        "",    // Iridium
        "",    // Platinum
        "",    // Gold
        "",    // Mercury
        "",    // Thallium
        "",    // Lead
        "",    // Bismuth
        "",    // Polonium
        "",    // Astatine
        "",    // Radon
        "",    // Francium
        "",    // Radium
        "",    // Actinium
        "",    // Thorium
        "",    // Protactinium
        "",    // Uranium
        "",    // Neptunium
        "",    // Plutonium
        "",    // Americium
        "",    // Curium
        "",    // Berkelium
        "",    // Californium
        "",    // Einsteinium
        "",    // Fermium
        "",    // Mendelevium
        "",    // Nobelium
        "",    // Lawrencium
        "",    // Rutherfordium
        "",    // Dubnium
        "",    // Seaborgium
        "",    // Bohrium
        "",    // Hassium
        "",    // Meitnerium
        "",    // Darmstadtium
        "",    // Roentgenium
        "",    // Ununbium
        "",    // Ununtrium
        "",    // Ununquadium
        "",    // Ununpentium
        "",    // Ununhexium
        "",    // Ununseptium
        "",    // Ununoctium
    };
}

#endif
