# This is a basic workflow to help you get started with Actions

name: Publish Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or merge events but only for the "main" branch
  push:
    branches: [ "gh-pages", "main" ]
  release:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs action to publish generated docs to gh-pages
      - name: Publish generated content to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2
        with:
          dir: docs/html
          branch: gh-pages
          
